name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [12, 14, 16]
        include:
          - node: 16
            os: ubuntu-latest
            full-ci: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - if: ${{ matrix.full-ci }}
        run: npm test config=@ci
        env:
          # Please get your own free key if you want to test yourself
          BROWSERSTACK_USERNAME: sitepenlabs1
          BROWSERSTACK_ACCESS_KEY: xm1uYrJuV3gZMJqCyZJX
      - if: ${{ ! matrix.full-ci }}
        run: npm test
      - if: ${{ matrix.full-ci }}
        uses: codecov/codecov-action@v2
